services:
  api: 
    build: 
      context: backend/
      secrets: 
        - dotnet_secrets
    ports:
      - "5001:8080"
    
  vue:
    build: frontend/
    ports:
      - 5000:80

  postgres:
    build: database/
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    secrets:
      - db_password  
    environment:
      POSTGRES_PASSWORD : /run/secrets/db_password 

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

secrets:
  dotnet_secrets:
    file: backend/dotnet_secrets.json
  db_password:
    file: database/dbpassword.txt