services:
  api:
    build:
      context: backend/
      secrets:
        - dotnet_secrets
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-app
    expose:
      - "8080"

  postgres:
    build: database/
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-db
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD : /run/secrets/db_password

  web:
    image: nginx:mainline
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/var/www/eventsib.dvfu.ru
    ports:
      - "80:80"

secrets:
  dotnet_secrets:
    file: backend/dotnet_secrets.json
  db_password:
    file: database/dbpassword.txt